### ISSUE TITLE
nimx build problem

### ISSUE THREAD

**Issue by alynch4047** [yglukhov/nimx#166]
I'm having some build problems, which may be due to my using 0.15 on Windows which I think has various issues. Anyway, first I hit that in ttf it couldn't find memory.h - and it doesn't seem to be in the mingw distributed with nim 0.15 - so I copied it from another mingw installation.

But then...

> nim c --threads:on -r sample01_welcome.nim

gives 

c:\users\alynch\.nimble\pkgs\nimx-0.1\nimx\view_event_handling.nim(14, 8) Error: method is not a base

any hints?

**Comment by yglukhov** [comment]
@alynch4047, I can't really tell what going on. My initial assumption is thats a nim issue. But anyway, the samples are intended to be run by compiling the `main.nim` file, or just run `nake`.

**Comment by alynch4047** [comment]
Yes I noticed a previous issue with nim, reported by your good self.
I did try running nake but ran into this same issue.

Thanks again for all your hard work on nimx, it looks very interesting and I'm keen to use it.

**Comment by yglukhov** [comment]
> I did try running nake but ran into this same issue.

Now that's getting strange because I can `nake` the samples just fine with latest nim devel. Can it be so that your nimx installation is corrupted in some way? Can you please try the following:
1. Verify that you have no nimx installed in nimble packages. Remove it if its there.
2. Then run nake in a freshly cloned nimx:
```
git clone https://github.com/yglukhov/nimx
cd nimx/test
nake
```

> Thanks again for all your hard work on nimx, it looks very interesting and I'm keen to use it.

Youre very welcome and thanks for your kind words. That is really inspiring.

**Comment by alynch4047** [comment]
OK great, I deleted the nimx found in my nimble\pkgs and now the build is all working, thanks!
