### ISSUE TITLE
Compile error (Arch linux, Newest version of nim)

### ISSUE THREAD

**Issue by Lite5h4dow** [yglukhov/nimx#346]
I get this error

`../../.nimble/pkgs/ttf-0.2.9/ttf/edtaa3func.nim(481, 33) Error: undeclared identifier: 'SomeReal'`

after compiling

```nim
# File: main.nim
import nimx.window
import nimx.text_field

proc startApp() =
    # First create a window. Window is the root of view hierarchy.
    var wnd = newWindow(newRect(40, 40, 800, 600))

    # Create a static text field and add it to view hierarchy
    let label = newLabel(newRect(20, 20, 150, 20))
    label.text = "Hello, world!"
    wnd.addSubview(label)

# Run the app
runApplication:
    startApp()
```
with
` nim c -r --threads:on main.nim `

**Comment by GammaSagittarii** [comment]
You need ttf-0.2.10. The easiest way is to remove .nimble folder and install nimx with all dependencies again.

**Comment by Lite5h4dow** [comment]
well now i did that and im getting this
```
nim c --threads:on main.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: main [Processing]
main.nim(2, 12) Error: cannot open file: nimx\window
```

**Comment by GammaSagittarii** [comment]
I am sorry if I was not clear enough, but you did not do what I said: remove .nimble folder (that you did do) and install nimx with all dependencies again - that means nimble install nimx. My solution is easiest for me, maybe not the most optimal. Nimble doesn't have an update function, and guessing which packages need updating because something is not working is really annoying,  so I just reinstall them all.  (I really wish nimble had sync function like pacman...)

**Comment by yglukhov** [comment]
Right. Please update `https://github.com/yglukhov/ttf`
